version: "2.2"
services:
  connector:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    container_name: swcorp-connector
    ports:
      - "7000:7000/tcp"
    networks: 
      - swcorp
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    privileged: true

networks:
  swcorp: {}